
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    groups:
      enabled: true

  swagger-ui:
    enabled : true
    path: /swagger-ui.html
    operations-sorter: method # GET, POST, PUT, DELETE 순으로 정렬
    tags-sorter: alpha        # 태그 이름 기준 알파벳 정렬
    display-request-duration: true  # API 요청 시간(응답 시간)을 표시
    doc-expansion: none             # 전부 접힘 상태로 시작
    persist-authorization: true
    default-models-expand-depth: -1


  cache:
    disabled: true # 캐시 비활성화

  springdoc:
    show-actuator: true

  profiles:
    default: local

spring:
  application:
    name: MockStock