spring:
  application:
    name: MockStock

  datasource:
    url: jdbc:mysql://localhost:3306/gaboja9
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gaboja9
    password: gaboja9!

  jpa:
    hibernate:
      ddl-auto: update
