name: Test
on:
  pull_request:
    branches: [ dev ]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PROJECT_DIR: MockStock
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew test
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Upload test report
        if: always()

        uses: actions/upload-artifact@v4
        with:
          name: junit-test-report
          path: ${{ env.PROJECT_DIR }}/build/reports/tests/test
          include-hidden-files: true
